#!/bin/bash
cd `dirname $0`

BUILD_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cross/bin/
ENV_VARS="-e OPT_FLAGS -e DEFS -e OUTPUT -e PATH=$BUILD_PATH"

if [ -t 1 ]
then
  INTERACTIVE=-it
fi

if [ $# -eq 0 ]
then
  COMMAND=bash
else
  COMMAND="$*"
fi

docker run $INTERACTIVE --privileged $ENV_VARS -v "`pwd`":/opt/src ${IMAGE:-peos-toolchain} $COMMAND
