#!/bin/bash
cd `dirname $0`

printf "change vnc password\n%s\n" password | qemu-system-i386 -s -vnc :0,password -kernel vmpeoz -no-reboot -no-shutdown -d pcall,cpu_reset,guest_errors -monitor stdio -initrd test.tar

