#!/bin/bash
cd `dirname $0`

case $1 in
  diskimage)
    qemu-system-i386 -s -drive format=raw,file=peos2.img -no-reboot -no-shutdown -d pcall,cpu_reset,guest_errors -monitor stdio
    ;;

  display)
    qemu-system-i386 -s -kernel kernel/vmpeoz -no-reboot -no-shutdown -d pcall,cpu_reset,guest_errors \
      -monitor stdio -initrd init.tar -append init=/ramfs/bin/shell
    ;;

  debug)
    qemu-system-i386 -s -S -kernel kernel/vmpeoz -no-reboot -no-shutdown -d pcall,cpu_reset,guest_errors \
      -monitor stdio -initrd init.tar -append init=/ramfs/bin/shell
    ;;

  vnc)
    printf "change vnc password\n%s\n" password | qemu-system-i386 -s -vnc :0,password -kernel kernel/vmpeoz \
      -no-reboot -no-shutdown -d pcall,cpu_reset,guest_errors -monitor stdio -initrd init.tar -append init=/ramfs/bin/shell_launcher
    ;;

  serial)
    qemu-system-i386 -nographic -s -kernel kernel/vmpeoz -no-reboot -d pcall,cpu_reset,guest_errors \
      -initrd init.tar -append init=/ramfs/bin/shell
    ;;

  *)
    echo $"Usage: $0 {diskimage|display|vnc|serial}"
    exit 1
esac

