export LIB_INCLUDE_DIR=..
export LIB_LIBRARY_DIR=..

all :
	$(MAKE) -C support

clean :
	$(MAKE) -C support clean

unittest :
	$(MAKE) -C support unittest

run-unittest :
	$(MAKE) -C support run-unittest

check :
	$(MAKE) -C support check

.PHONY : all clean unittest check

